name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: inject script
        run: sed -i 's@</body>@<script src="https://hypothes.is/embed.js" async></script></body>@' index.html
      
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
          with:
            repository-name: rongbinf/logseq-publish
            branch: main
            folder: .
